### ISSUE TITLE
Error on startup: cannot import name 'SERVICE_WRITE_COIL_SCHEMA

### ISSUE THREAD

**Issue by akram** [yury-sannikov/hass-modbus-slave#2]
## Version of the custom_component
latest

## Configuration

```yaml


modbus_slave:
    type: tcpserver
    host: 0.0.0.0
    port: 5020
    bit_switches:
      - name: disable_bypass
        slave: 77
        address: 3
        command_bit_number: 5
        status_bit_number: 5
    sensors:
      - name: live_counter
        slave: 77
        address: 2
        data_type: uint

```

## Describe the bug
I am getting the following error when the components tries to start:

```
Setup failed for custom integration modbus_slave: Unable to import component: cannot import name 'SERVICE_WRITE_COIL_SCHEMA' from 'homeassistant.components.modbus' (/usr/src/homeassistant/homeassistant/components/modbus/__init__.py)
```

## Debug log

```text

```
Setup failed for custom integration modbus_slave: Unable to import component: cannot import name 'SERVICE_WRITE_COIL_SCHEMA' from 'homeassistant.components.modbus' (/usr/src/homeassistant/homeassistant/components/modbus/__init__.py)
```

```
